### ISSUE TITLE
Example for using in the browser

### ISSUE THREAD

**Issue by RedTn** [picode7/fbx-parser#2]
Is there an example on how to use this in the browser? `fs` doesn't exist as a module on that.
I tried filereader and it seems to work fine but for binary files it's a bit tricky

**Comment by picode7** [comment]
Hi RedTn, did you try using `readAsArrayBuffer`?

```html
<input type="file" id="file-input" />
```
```js
document.getElementById('file-input').addEventListener(
  'change',
  (e) => {
    const file = e.target.files[0]
    if (!file) return
    
    const reader = new FileReader()
    reader.onload = (e) => {
      const contents = e.target.result
      const binary = new Uint8Array(contents)
    }
    reader.readAsArrayBuffer(file)
  }
)
```

**Comment by RedTn** [comment]
Yea I tried, but thanks this is a good example.
I thought the issue was how I was using the library, but it seems that there were some .fbx files it could not parse properly
https://github.com/Unity-Technologies/Graphics/blob/3a3be86f669c1e8681eeaacdd57742047b5912e4/com.unity.template-universal/Assets/ExampleAssets/Models/safetyhat_low.fbx

**Comment by picode7** [comment]
Interesting. The Autodesk FBX converter that I used on other files for checking gets an error: `Call to FbxImporter::Import() failed. Error: File is corrupted`, however it does open in other editors like 3ds Max and the default Windows 3D Viewer.

Debugging the binary parser I can see that this FBX file has an empty root node, but the name of the second node is read too long `ExtensiontFBXHeaderVersionIë`, which then leads to issues interpreting the rest of the data.

I'll have to check what is different in this file from the FBX Binary documentation provided by Blender.

**Comment by RedTn** [comment]
Cool, good to know thanks. Since the initial issue was for an example in the browser, I'll close this.

**Comment by picode7** [comment]
@RedTn the other issue has been fixed: https://github.com/picode7/fbx-parser/issues/3
